version: "3.8"

services:

  db:
    container_name: postgressql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: app
    build:
      dockerfile: ops/infra/Dockerfile
      context: ../../
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - /Users/sarvesh/Public/personal/fast-api/app:/app
    restart: always
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379

